spring:
  data:
    mongodb:
      user: root
      password: root
      uri: mongodb://root:root@localhost:27017/register?authSource=admin
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /rent/v1/
